Issue #86 Add a callback to filter sections from course format
Syxton/moodle-block_massaction pull request #92
Opened 2023-10-18 23:04 UTC by TomoTsuyuki

Implement callback function `massaction_restricted_sections` to filter sections for preventing move/copy.

Course format plugin can implement **_pluginname_**_massaction_restricted_sections in their `lib.php` and filter the sections from the course format rule.

The parameter for the **_pluginname_**_massaction_restricted_sections is courseid, and returns array of sections.

2023-10-20 04:36 UTC, TomoTsuyuki commented
This is for issue #86

2023-10-25 02:16 UTC, TomoTsuyuki commented
Rebased with the latest `master` branch.

2024-01-10 14:52 UTC, Syxton commented on classes/actions.php
> +                continue;
Should we throw an exception of sectionrestricted here?

2024-01-10 14:55 UTC, Syxton commented on classes/actions.php
> +                continue;
Should we throw an exception of sectionrestricted here?

2024-01-10 14:55 UTC, Syxton commented on classes/actions.php
> +                continue;
Should we throw an exception of sectionrestricted here?

2024-01-10 14:56 UTC, Syxton requested changes
I like these changes, but it seems we might want to throw an exception if we somehow get to a restricted section instead of skipping past it.  What do you think?

2024-01-11 17:15 UTC, merged